rootProject.name = "libcommon"
include(":libcommon-aliyunons")
include(":libcommon-bom")
include(":libcommon-collection")
include(":libcommon-jdbc")
include(":libcommon-json")
include(":libcommon-json-dsljson")
include(":libcommon-json-jackson2")
include(":libcommon-json-jsoniter")
include(":libcommon-redis")
include(":libcommon-rocketmq")
include(":libcommon-util")
